SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM vrs_franchise;
DELETE FROM vrs_abstract_billitem;
DELETE FROM vrs_account;
DELETE FROM vrs_account_year;
DELETE FROM vrs_bill;
DELETE FROM vrs_billitem;
DELETE FROM vrs_billitem_subitem;
DELETE FROM vrs_credit_billitem;
DELETE FROM vrs_credit_paymentitem;
DELETE FROM vrs_detail_info;
DELETE FROM vrs_doc;
DELETE FROM vrs_driver;
DELETE FROM vrs_header_info;
DELETE FROM vrs_doc_issuance;
DELETE FROM vrs_payment;
DELETE FROM vrs_paymentitem;
DELETE FROM vrs_txn;
DELETE FROM vrs_txn_task;
DELETE FROM vrs_account_case;
DELETE FROM sys_sequence;
SET FOREIGN_KEY_CHECKS = 1;