DROP VIEW IF EXISTS vw_water_account;
CREATE VIEW vw_water_account AS 
SELECT
ma.*,
mai.acctname,
mai.owner_name,
mai.owner_address_text,
mai.owner_entitytype,
mai.owner_profileid,
mai.owner_profileno,
mai.owner_firstname,
mai.owner_lastname,
mai.owner_middlename,
mai.owner_resident,
mai.owner_address_unitno,
mai.owner_address_bldgno,
mai.owner_address_bldgname,
mai.owner_address_street,
mai.owner_address_subdivision,
mai.owner_address_barangay_objid,
mai.owner_address_barangay_name,
mai.owner_address_citymunicipality,
mai.owner_address_province,
mai.owner_tin,
mai.owner_email,
mai.owner_mobileno,
mai.owner_phoneno,
mai.owner_id_type_name,
mai.owner_id_idno,
mai.owner_id_placeissued,
mai.owner_id_dtissued,
mai.contact_mobileno,
mai.contact_email,
mai.contact_phoneno,
mai.meterid,
mai.meterstatus,
mai.classificationid,
mai.classification_objid,
mai.classification_name,

mai.location_text,
mai.location_unitno,
mai.location_bldgno,
mai.location_bldgname,
mai.location_blockno,
mai.location_lotno,
mai.location_street,
mai.location_subdivision,
mai.location_barangay_objid,
mai.location_barangay_name,
mai.location_lng,
mai.location_lat,

mai.business_objid,	
mai.business_bin,	
mai.business_tradename,	
mai.units,
mai.tags,
wag.objid AS acctgroupid,
wag.name AS acctgroup_name,
wag.fullpath AS acctgroup_fullpath,
wag.leftindex AS acctgroup_sortorder,


mai.metered,
mai.meter_objid,
mai.meter_serialno,
mai.meter_brand,
mai.meter_capacity,
mai.meter_sizeid, 
mai.meter_customerowned,
mai.meter_stocktype,
mai.meter_state,
mai.meter_size_objid,
mai.meter_size_title,
mai.meter_supersededid,

t.state AS task_state,
t.dtcreated AS task_dtcreated,
t.startdate AS task_startdate,
t.enddate AS task_enddate,
t.assignee_objid AS task_assignee_objid,
t.assignee_name AS task_assignee_name,
t.actor_objid AS task_actor_objid,
t.actor_name AS task_actor_name,
sn.title AS task_title,
sn.tracktime AS task_tracktime,
sn.properties AS task_properties,
mai.notes,

(wb.balanceforward + wb.interest + wb.surcharge + wb.amount) - (wb.totalpayment + wb.discount) AS bill_balance,
bs.year AS bill_year,
bs.month AS bill_month,
bs.groupid as schedulegroupid,
t.state,
ma.acctno AS cashreceiptrefid 

FROM water_account ma
INNER JOIN vw_water_account_info mai ON ma.acctinfoid = mai.objid
INNER JOIN water_account_task t ON ma.taskid = t.taskid 
INNER JOIN sys_wf_node sn ON sn.processname = 'water_account' AND sn.name = t.state
LEFT JOIN water_billgroup wbg ON ma.billgroupid = wbg.objid 
LEFT JOIN water_acctgroup wag ON mai.acctgroupid = wag.objid 
LEFT JOIN water_bill wb ON wb.objid = ma.lastbillid  
LEFT JOIN water_billschedule bs ON wb.scheduleid = bs.objid 
